'use strict';
(async()=>{
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data;
try{const res=await fetch('./operators-data.json?v=20260914-1');if(!res.ok)throw Error('load');data=await res.json();}catch{$('result-count').textContent='도감을 불러오지 못했습니다. 페이지를 새로고침해 주세요.';return;}
const ops=data.operators.sort((a,b)=>b.rarity-a.rarity||a.name.localeCompare(b.name,'ko')),power=id=>data.powers[id]||id,controls=['op-search','op-prof','op-rarity','op-nation','op-group','op-birth'];
let selected=null,filtered=[],page=0;const perPage=24;
function fill(id,values,label=x=>x){$(id).insertAdjacentHTML('beforeend',[...new Set(values)].sort((a,b)=>label(a).localeCompare(label(b),'ko')).map(x=>`<option value="${esc(x)}">${esc(label(x))}</option>`).join(''));}
fill('op-prof',ops.map(o=>o.profession));fill('op-nation',ops.map(o=>o.nation),power);fill('op-group',ops.flatMap(o=>o.groups),power);fill('op-birth',ops.map(o=>o.birthplace));
$('total-count').textContent=ops.length+'명';$('data-date').textContent=`데이터 ${data.date} · 확인 ${data.checked}`;
function search(){page=0;const term=$('op-search').value.trim().toLocaleLowerCase();filtered=ops.filter(o=>{const hay=[o.name,o.english,o.profession,o.branch,power(o.nation),...o.groups.map(power),...o.secondary.map(power),o.birthplace,o.race].join(' ').toLocaleLowerCase();return (!term||hay.includes(term)||term==='염국'&&o.nation==='yan')&&(!$('op-prof').value||o.profession===$('op-prof').value)&&(!$('op-rarity').value||o.rarity===Number($('op-rarity').value))&&(!$('op-nation').value||o.nation===$('op-nation').value)&&(!$('op-group').value||o.groups.includes($('op-group').value))&&(!$('op-birth').value||o.birthplace===$('op-birth').value);});if(!filtered.some(o=>o.id===selected?.id)){selected=filtered[0]||null;renderDetail();}renderList();}
function renderList(){const pages=Math.ceil(filtered.length/perPage);$('result-count').textContent=`${filtered.length}명 · 희귀도 높은 순 / 이름순`;$('operator-list').innerHTML=filtered.length?filtered.slice(page*perPage,(page+1)*perPage).map(o=>`<button class="operator-row" type="button" data-operator="${esc(o.id)}" aria-pressed="${o.id===selected?.id}"><span class="row-star">${'★'.repeat(o.rarity)}</span><strong>${esc(o.name)}</strong><span>${esc(o.profession)} · ${esc(o.branch)}</span><span>소속 ${esc([power(o.nation),...o.groups.map(power)].join(' / '))} · 출신 ${esc(o.birthplace)}</span></button>`).join(''):'<p class="empty-result">조건에 맞는 오퍼레이터가 없습니다. 필터를 바꿔 주세요.</p>';$('page-count').textContent=pages?`${page+1} / ${pages}`:'0 / 0';$('previous').disabled=page===0;$('next').disabled=page>=pages-1;}
function fact(k,v){return `<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`;}
function skillBody(s,i){const x=s.levels[i];return `<p class="skill-meta">${esc(x.activation)} · ${esc(x.recovery)} · 초기 SP ${x.initial} / 필요 SP ${x.sp}${x.duration>0?' · 지속 '+x.duration+'초':''}</p><p>${esc(x.description)}</p>`;}
function renderDetail(){if(!selected){$('operator-detail').innerHTML='<p>조건에 맞는 오퍼레이터를 찾아보세요.</p>';return;}const o=selected;document.title=`${o.name} · Arknights INFO`;
$('operator-detail').innerHTML=`<div class="op-heading"><p class="eyebrow">${o.rarity}성 / ${esc(o.profession)} · ${esc(o.branch)}</p><h2>${esc(o.name)}</h2><p>${esc(o.english)} · ${esc(o.position)}</p></div><dl class="op-facts">${fact('주 소속 국가',power(o.nation))}${fact('주 소속 조직·팀',o.groups.map(power).join(' / ')||'별도 표기 없음')}${fact('프로필 출신지',o.birthplace)}${fact('종족',o.race)}${o.secondary.length?fact('보조 소속 · 게임 데이터',o.secondary.map(power).join(' / ')):''}</dl><p class="op-tags">${esc(o.tags.join(' · '))}</p><section class="op-section"><h3>특성</h3><p>${esc(o.trait)}</p></section><section class="op-section"><h3>기본 능력치</h3><p class="stat-note">${o.phase}정예 · 레벨 ${o.level} · 신뢰도 능력치 최대 / 잠재능력·모듈·재능 효과 제외</p><div class="stat-grid">${[['최대 HP','maxHp'],['공격력','atk'],['방어력','def'],['마법 저항','magicResistance'],['배치 코스트','cost'],['저지 수','blockCnt'],['공격 간격(초)','baseAttackTime'],['재배치(초)','respawnTime']].map(([k,v])=>`<div><small>${k}</small><b>${o.stats[v]}</b></div>`).join('')}</div></section><section class="op-section"><h3>재능</h3><p class="stat-note">최종 정예 · 잠재능력 강화 전</p>${o.talents.length?o.talents.map(t=>`<h4>${esc(t.name)}</h4><p>${esc(t.description)}</p>`).join(''):'<p>별도 재능 없음</p>'}</section><section class="op-section"><h3>스킬</h3>${o.skills.map((s,i)=>`<article class="skill-card"><div class="skill-top"><h4>S${i+1} · ${esc(s.name)}</h4><select data-skill="${i}" aria-label="${esc(s.name)} 레벨">${s.levels.map((l,j)=>`<option value="${j}" ${j===Math.min(6,s.levels.length-1)?'selected':''}>${l.label}</option>`).join('')}</select></div><small class="skill-meta">${s.phase}정예 해금</small><div data-skill-body="${i}">${skillBody(s,Math.min(6,s.levels.length-1))}</div></article>`).join('')||'<p>별도 스킬 없음</p>'}</section><section class="op-section"><h3>모듈</h3>${o.modules.map(m=>`<article class="module-card"><h4>${esc(m.type)} · ${esc(m.name)}</h4><p class="skill-meta">${esc(m.unlock)}${m.special?' · '+esc(m.special):''}</p>${m.stages.map(s=>`<details><summary>${s.level}단계 · ${esc(s.stats.join(' / '))}</summary>${s.effects.map(e=>`<p>${esc(e)}</p>`).join('')||'<p>추가 설명 없음</p>'}</details>`).join('')}</article>`).join('')||'<p>수록된 모듈 없음</p>'}</section>`;}
$('filters').addEventListener('submit',e=>e.preventDefault());controls.forEach(id=>$(id).addEventListener(id==='op-search'?'input':'change',search));$('filters').addEventListener('reset',()=>{setTimeout(search,0);});
$('operator-list').addEventListener('click',e=>{const b=e.target.closest('[data-operator]');if(!b)return;selected=ops.find(o=>o.id===b.dataset.operator);history.replaceState(null,'','#'+selected.id);renderDetail();renderList();if(matchMedia('(max-width:760px)').matches){$('operator-detail').scrollIntoView({block:'start'});$('operator-detail').focus({preventScroll:true});}else document.querySelector(`[data-operator="${selected.id}"]`)?.focus();});
$('operator-detail').addEventListener('change',e=>{const i=e.target.dataset.skill;if(i===undefined)return;document.querySelector(`[data-skill-body="${i}"]`).innerHTML=skillBody(selected.skills[Number(i)],Number(e.target.value));});
$('previous').addEventListener('click',()=>{if(page>0){page--;renderList();$('operator-list').scrollTop=0;}});$('next').addEventListener('click',()=>{if((page+1)*perPage<filtered.length){page++;renderList();$('operator-list').scrollTop=0;}});
function fromHash(){const o=ops.find(x=>x.id===location.hash.slice(1));if(o){selected=o;controls.forEach(id=>$(id).value='');filtered=ops;page=Math.floor(ops.indexOf(o)/perPage);renderDetail();renderList();}}
search();fromHash();window.addEventListener('hashchange',fromHash);
})();
